# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kiyeon's Blog
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  All writing and photography is by Kiyeon, licensed CC BY-NC 4.0. Everything else is under copyright unless otherwise noted.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  kiyeon

# Build settings
markdown: kramdown
